spring:
  profiles:
    active: local

---
spring:
  profiles: local

  master:
    datasource:
      url: jdbc:mysql://127.0.0.1/namu_db
      driver-class-name: com.mysql.jdbc.Driver
      username: web_dev
      password: 1234

  slave:
    datasource:
      url: jdbc:mysql://127.0.0.1/namu_db
      driver-class-name: com.mysql.jdbc.Driver
      username: web_dev
      password: 1234
---
